version: '0.2'
ignorePaths: ['archive', 'node_modules']
dictionaries:
  - 'en_US'
  - 'softwareTerms'
  - 'bash'
  - 'node'
  - 'npm'
  - 'html'
  - 'css'
  - 'typescript'
  - 'filetypes'
words: ['vitepress', 'vssue', 'treeshake']
ignoreWords: ['preinstall', 'trivago']
